### ISSUE TITLE
Improve components architecture schema

### ISSUE THREAD

**Issue by alexbaumgertner** [GriddleGriddle/griddle-docs#7]
It's hard to read monotonic picture http://griddlegriddle.github.io/Griddle/docs/architecture/.

May be create HTML based schema like this: https://jsbin.com/zomowap/edit?html,css,output
![js bin - collaborative javascript debugging 2017-04-06 15-57-10](https://cloud.githubusercontent.com/assets/223620/24755150/c373fde0-1ae1-11e7-911b-32ceb91e5025.png)

(gist: https://gist.github.com/alexbaumgertner/247dc144c4db61222f7a75cbf104e32b)

**Comment by ryanlanciaux** [comment]
That is way clearer.
